# Generated by Django 4.0.7 on 2022-12-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Team', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=20)),
                ('Picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
