# Generated by Django 4.0.7 on 2022-12-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtrackerapp', '0003_registerdetails_status_registerdetails_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdetails',
            name='Email',
            field=models.CharField(max_length=30),
        ),
    ]
