# Generated by Django 4.0.7 on 2022-12-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtrackerapp', '0004_alter_registerdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.FileField(upload_to='')),
                ('Deadline', models.DateTimeField()),
            ],
        ),
    ]
