# Generated by Django 4.0.7 on 2022-12-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questtrackerapp', '0006_alter_assignproject_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assignproject',
        ),
        migrations.DeleteModel(
            name='registerdetails',
        ),
    ]
