# Generated by Django 4.0.7 on 2022-12-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questtrackerapp', '0007_delete_assignproject_delete_registerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.FileField(upload_to='')),
                ('Deadline', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Team', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=20)),
                ('Picture', models.FileField(upload_to='')),
                ('Status', models.BooleanField(default=False)),
                ('Verification', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
