# Generated by Django 4.0.7 on 2022-12-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtrackerapp', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignproject',
            name='Project_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerdetails',
            name='Teamlead',
            field=models.BooleanField(default=False),
        ),
    ]
