# Generated by Django 4.0.7 on 2022-12-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtrackerapp', '0010_alter_assignproject_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdetails',
            name='Teamlead',
            field=models.CharField(max_length=20),
        ),
    ]
