# Generated by Django 4.0.7 on 2023-01-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtrackerapp', '0013_assignprojecttoteam_remove_assignproject_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdetails',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='registerdetails',
            name='Verification',
        ),
        migrations.AddField(
            model_name='assignprojecttoteam',
            name='Project_Report',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignprojecttoteam',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignprojecttoteam',
            name='Teamlead',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='assignprojecttoteam',
            name='Verification',
            field=models.BooleanField(default=False),
        ),
    ]
