# Generated by Django 4.0.7 on 2023-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtrackerapp', '0014_remove_registerdetails_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignprojecttoteam',
            name='Submit',
            field=models.BooleanField(default=False),
        ),
    ]
